inference_gpu_ids = [0]
trainer_gpu_ids = [1]

max_steps = 20

[model]
name = "PrimeIntellect/Qwen3-0.6B-Reverse-Text-SFT"

[wandb]
project = "reverse-text-debug"
name = "reverse-text-0.6b"

[trainer.optim]
lr = 3e-6
weight_decay = 0.0

[orchestrator]
batch_size = 128
rollouts_per_example = 16
seq_len = 2048
mask_truncated_completions = false
zero_truncated_completions = true
oversampling_factor = 2.0

[orchestrator.sampling]
max_tokens = 128

[orchestrator.buffer]
filter_min_threshold = 0.0
filter_max_threshold = 1.0

[[orchestrator.env]]
id = "reverse-text"
